config/routes.rb
Rails.application.routes.draw do
  resources :fermas
  resources :proxies
  resources :projects do
    resources :tasks
  end
  devise_for :users

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  get '/parser/', to: 'parser#index'
  get '/adminka/', to: 'adminka#index'
  post '/projects/:project_id/tasks/:id/status', to: 'tasks#status'
  post '/fermas/checkssl/', to: 'fermas#checkssl'
  post '/fermas/status200/', to: 'fermas#status200'
  post '/fermas/delete_proxy/', to: 'fermas#delete_proxy'
  post '/adminka/setstatus/', to: 'adminka#setstatus'
  post '/proxies/create/', to: 'proxies#create'

  root 'index#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project
  validates :name, presence: true
  validates :status, presence: true, length: { in: 1..5 }
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_task, only: [:status, :show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token, :only => [:status]

  def create
    @project = Project.find(params[:project_id])
    @task = @project.tasks.create(task_params)
    redirect_to project_path(@project)

  end

  def show  
  end

  def edit    
  end
  
  def update
    @project = Project.find(params[:project_id])
    @task = @project.tasks.find(params[:id])
    if @task.update(task_params)
      redirect_to project_path(@project)
  end
  end
  
  def status
    @project = Project.find(params[:project_id])
    @task = @project.tasks.find(params[:id])
    st = params[:status]
    @task.update(status: st)
    
  end
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @project = Project.find(params[:project_id])
      @task = @project.tasks.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:name, :title, :status, :project_id)
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
    def status_to number
        case number
            when 1
                return '<span class="status-importanty">Важный</span>'
            when 2
                return '<span class="status-medium">Средний</span>'
            when 3
                return '<span class="status-defer">Можно отложить</span>'
            when 4
                return '<span class="status-ready">Готово</span>'
            when 5
                return '<span class="status-test"> Протестировано</span>'
        end
    end

end

app/views/tasks/_form.html.slim
= form_with(model: [@project, @task], local:true) do |f|
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :title
    = f.text_area :title, :class => "tinymce", :rows => 10, :cols => 120
  .field
    = f.label :status
    = f.number_field :status
  .actions = f.submit

app/views/tasks/edit.html.slim
h1 Editing task

== render 'form'

app/views/tasks/index.html.slim
h1 Listing tasks

table
  thead
    tr
      th Name
      th Title
      th Status
      th Project
      th
      th
      th

  tbody
    - @tasks.each do |task|
      tr
        td = task.name
        td = task.title
        td = task.status
        td = task.project
        td = link_to 'Show', task
        td = link_to 'Edit', edit_task_path(task)
        td = link_to 'Destroy', task, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Task', new_task_path

app/views/tasks/new.html.slim
h1 New task

== render 'form'

= link_to 'Back', tasks_path

app/views/tasks/show.html.slim
= csrf_meta_tags
p#notice = notice
h3  = @task.project.name
.task_header
  p
    strong Задача: 
    = @task.name  
  p
    |
    strong = status_to(@task.status).html_safe
    select#status name="status"
      option value="1" Важно
      option value="2" Средний
      option value="3" Можно отложить
      option value="4" Готово
      option value="5" Протестировано

.task_description
  p
    strong Описание: 
    = @task.title.html_safe

  h4 Добавить комментарий
.block_comment
//
//= form_with(model: [@task, task.project.update], local:true) do |f|
//  .field
//    = f.label :status
//    = f.number_field :status
//  .actions = f.submit

=< link_to 'Back', project_path(@project)

app/views/tasks/status.slim
= @task.name
= @st