config/routes.rb
Rails.application.routes.draw do
  resources :fermas
  resources :proxies
  resources :projects do
    resources :tasks
  end
  devise_for :users

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  get '/parser/', to: 'parser#index'
  get '/adminka/', to: 'adminka#index'
  post '/projects/:project_id/tasks/:id/status', to: 'tasks#status'
  post '/fermas/checkssl/', to: 'fermas#checkssl'
  post '/fermas/status200/', to: 'fermas#status200'
  post '/fermas/delete_proxy/', to: 'fermas#delete_proxy'
  post '/adminka/setstatus/', to: 'adminka#setstatus'
  post '/proxies/create/', to: 'proxies#create'

  root 'index#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/index/_projects.html.slim
.project
    .project__head
        = link_to 'Проекты', projects_path
    .project__body
        ul
            - @projects.each do |p|
                li 
                    |
                    = image_tag p.image.thumb('20x20#').url
                    
                    = p.name

app/views/index/index.html.slim
h1 ProjectManagmentSystem

.container-fluid
    - if user_signed_in?
        .wrap
            = render 'projects'
            .tools
                .tools__header
                    p Инструменты
                .tools__body
                   p = link_to 'Ферма', fermas_path
                   p = link_to 'Прокси', proxies_path
    
        .helper.col-md-5
            h4 Инструкция по добавлению сателлита
            ol
                li 
                    | Добавь в список новый 
                    = link_to 'Прокси', proxies_path
                    ul
                        li Если к сателлиту Прокси не определен, тогда выбери из списка существующий прокси. 
                li 
                    | Добавь сателлит 
                    = link_to 'Ферма', fermas_path 
                    ul
                        li Послед добавления сателлита в Ферму, желательно указать второй прокси. Первый - основной прокси. Второй - на случай если основной прокси ляжет. Кол-во прокси у сателлита может быть не ограниченно. 
                        li 
                            |
                            strong Важно!
                            span  Система проверяет только первые 2 прокси. 

    -else
        p Для получения дополнительных функций надо войти в систему