config/routes.rb
Rails.application.routes.draw do
  resources :fermas
  resources :proxies
  resources :projects do
    resources :tasks
  end
  devise_for :users

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  get '/parser/', to: 'parser#index'
  get '/adminka/', to: 'adminka#index'
  post '/projects/:project_id/tasks/:id/status', to: 'tasks#status'
  post '/fermas/checkssl/', to: 'fermas#checkssl'
  post '/fermas/status200/', to: 'fermas#status200'
  post '/fermas/delete_proxy/', to: 'fermas#delete_proxy'
  post '/adminka/setstatus/', to: 'adminka#setstatus'
  post '/proxies/create/', to: 'proxies#create'

  root 'index#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ferma.rb
class Ferma < ApplicationRecord    
	has_one :whoi, dependent: :destroy
	belongs_to :user
	has_and_belongs_to_many :proxies
	
	validates :date_create_hosting, presence: true, length: { in: 1..15 }
	validates :url, presence: true, length: { in: 1..50 }
	validates_associated :proxies
	validates :url, format: { with: /\Ahttps:\/\/(www)?\..*\z/, message: 'URL invalid!' }
end

app/controllers/fermas_controller.rb
class FermasController < ApplicationController
  before_action :authenticate_user!
  before_action :set_ferma, only: [:show, :edit, :update, :destroy]


  # GET /fermas
  # GET /fermas.json
  def index
    @statuses = {}
    if current_user.status == 'admin'|| current_user.status == 'happy'
      @fermas = Ferma.all
    elsif current_user.status == 'manager'
      id = current_user.id
      @fermas = Ferma.where(user_id:id)
    else
      redirect_to root_path
    end
  end

  # GET /fermas/1
  # GET /fermas/1.json
  def show
  end

  # GET /fermas/new
  def new
    @ferma = Ferma.new
    @proxies = Proxy.all  
  end

  # GET /fermas/1/edit
  def edit
    @proxies = Proxy.all    
  end

  # POST /fermas
  # POST /fermas.json
  def create
    @ferma = Ferma.new(ferma_params)
    @ferma.user_id = current_user.id
    proxy = Proxy.where(id: params[:proxy])
    @ferma.proxies << proxy
    whois = Whoi.create(ferma_id: @ferma.id, expires: whois(@ferma.url))
    @ferma.whoi = whois
    respond_to do |format|
      if @ferma.save
        format.html { redirect_to @ferma, notice: 'Ferma was successfully created.' }
        format.json { render :show, status: :created, location: @ferma }
      else
        format.html { render :new }
        format.json { render json: @ferma.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fermas/1
  # PATCH/PUT /fermas/1.json
  def update
    whois = Whoi.create(ferma_id: @ferma.id, expires: whois(@ferma.url))
    @ferma.whoi = whois
    respond_to do |format|
      if @ferma.update(ferma_params)
        proxy = Proxy.where(id: params[:proxy])
        @ferma.proxies << proxy if !@ferma.proxies.include? proxy[0]      
        
        format.html { redirect_to @ferma, notice: 'Ferma was successfully updated.' }
        format.json { render :show, status: :ok, location: @ferma }
      else
        format.html { render :edit }
        format.json { render json: @ferma.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fermas/1
  # DELETE /fermas/1.json
  def destroy
    if current_user.status == 'admin' || current_user.status == 'happy'
      @ferma.destroy
      respond_to do |format|
        format.html { redirect_to fermas_url, notice: 'Ferma was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  def delete_proxy
    #puts params[:proxy_id]
    @site = Ferma.find(params[:ferma_id])
    @site.proxies.delete(Proxy.find(params[:proxy_id]))
    #render html: "OK"
    redirect_to ferma_path(params[:ferma_id])
  end
  
  require "http"
  def status200
    url = params[:url].to_s
    site = Ferma.where(url: url)[0]
    @response = if site.proxies[0]
                  ip_proxy = site.proxies[0].url
                  port_roxy = site.proxies[0].port
                  login_proxy = site.proxies[0].login
                  pass_proxy = site.proxies[0].password
                  begin
                    status = HTTP.via(ip_proxy, port_roxy, login_proxy, pass_proxy).head(url).status
                  rescue Exception => e
                    puts e
                    if site.proxies[1]
                      begin
                        status = HTTP.via(site.proxies[1].url,  site.proxies[1].port, site.proxies[1].login,   site.proxies[1].password).head(url).status
                      rescue Exception => e
                        status = e
                      end
                    else
                      status = e
                    end
                  end
                  if status==200
                    add_class = "success"
                  else 
                    add_class = "bg-warning"                   
                  end
                  @response = {"status": status, "class": add_class}
                  #Status
                  #407 Proxy Authentication Required
                else
                  '{"status":"No Proxy", "class": "bg-warning"}'
                end
    render :json => @response
  end  

  require 'ssl_scanner'
  def checkssl    
    url = params[:url].to_s
    ssl = SslScanner.scan_domain(url) 
    @data = "Expires: #{ssl[:expires]} <br>
             Check: #{ssl[:issuer]}"
    render :html => @data.html_safe
  end

  private

    require "whois-parser"
    require "addressable/uri"
    def whois url    
      uri = Addressable::URI.parse url
      data = Whois.whois(uri.host.gsub(/www./, ''))
      return data.parser.expires_on    
    end  

    # Use callbacks to share common setup or constraints between actions.
    def set_ferma
      @ferma = Ferma.find(params[:id])
    end
    
    # Never trust parameters from the scary internet, only allow the white list through.
    def ferma_params
      params.require(:ferma).permit(:date_create_hosting, :name, :url, :hoster, :description, :user_id)
    end
end

app/helpers/fermas_helper.rb
require "whois-parser"
require 'ssl_scanner'
require "addressable/uri"

module FermasHelper
   
    def check_ssl url        
            ssl = SslScanner.scan_domain(url) 
            data = "Expires: #{ssl[:expires]} <br>
                    Check: #{ssl[:issuer]}"   
            return data  
    end

    def dns url
        uri = Addressable::URI.parse url
        #data = Whois.whois uri.host.gsub(/www./, '')
        return uri #data.parser.expires_on
    end
    

end

app/views/fermas/_form.html.slim
= form_for @ferma do |f|
  - if @ferma.errors.any?
    #error_explanation
      h2 = "#{pluralize(@ferma.errors.count, "error")} prohibited this ferma from being saved:"
      ul
        - @ferma.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :url
    = f.text_field :url
  .field
    = f.label :hoster
    = f.text_field :hoster
  .field
    = f.label :date_create_hosting
    = f.text_field :date_create_hosting
  .field
    = f.label :description
    = f.text_area :description
  .field
    select name="proxy"
      - @proxies.each do |proxy|
        option value="#{proxy.id}" title="#{proxy.url}" = proxy.name
  .actions = f.submit

app/views/fermas/edit.html.slim
h1 Editing ferma

== render 'form'

=> link_to 'Show', @ferma
'|
=< link_to 'Back', fermas_path

app/views/fermas/index.html.slim
h1 Ferma
button id="check" Check

table class="table"
  thead
    tr class="dark"
      th Name
      th Url
      th Status
      th class="" Check SSL
      th DNS
      th Date reg
      th
      th
      th
  - r = Redis.new
  tbody
    - @fermas.each do |ferma|
      tr
        th class="info strong" = ferma.name
        td class="url" = ferma.url
        td class="status" = r.get(ferma.url)
        td class="ssl" = check_ssl(ferma.url).html_safe
        td class="dns" = ferma.whoi.expires if ferma.whoi
        td class="date" = ferma.date_create_hosting
        td = link_to 'Show', ferma
        td = link_to 'Edit', edit_ferma_path(ferma)
        td = link_to 'x', ferma, class: "delete", role: "button", data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Ferma', new_ferma_path

app/views/fermas/new.html.slim
h1 New ferma

== render 'form'

= link_to 'Back', fermas_path

app/views/fermas/show.html.slim
p#notice = notice

p
  strong Name: 
  = @ferma.name
p
  strong Url: 
  = @ferma.url
p
  strong Hoster: 
  = @ferma.hoster
p
  strong Date reg: 
  = @ferma.date_create_hosting
p
  strong Description: 
  = @ferma.description

 
strong Use Proxy: 
table.tbl-proxy_list_from_ferma
  - @ferma.proxies.each do |proxy|
    tr 
      td
        = proxy.url
      td
        button.btn.btn-danger.js-btn-destroy-proxy data-proxy_id="#{proxy.id}" data-ferma_id="#{@ferma.id}" x

=> link_to 'Edit', edit_ferma_path(@ferma)
'|
=< link_to 'Back', fermas_path