config/routes.rb
Rails.application.routes.draw do
  resources :fermas
  resources :proxies
  resources :projects do
    resources :tasks
  end
  devise_for :users

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  get '/parser/', to: 'parser#index'
  get '/adminka/', to: 'adminka#index'
  post '/projects/:project_id/tasks/:id/status', to: 'tasks#status'
  post '/fermas/checkssl/', to: 'fermas#checkssl'
  post '/fermas/status200/', to: 'fermas#status200'
  post '/fermas/delete_proxy/', to: 'fermas#delete_proxy'
  post '/adminka/setstatus/', to: 'adminka#setstatus'
  post '/proxies/create/', to: 'proxies#create'

  root 'index#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/project.rb
class Project < ApplicationRecord

    has_many :tasks, dependent: :destroy

    dragonfly_accessor :image

    validates_presence_of :name
 
    #image validations
    validates_presence_of :image
    validates_size_of :image, maximum: 600.kilobytes,
                      message: "should not be more than 600KB", if: :image_changed?
   
    validates_property :format, of: :image, in: ['jpeg', 'png', 'gif'],
                        message: "the formats allowed are: .jpeg, .png, .gif", if: :image_changed?
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name,:image)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form-task.html.slim
= form_with(model: [@project, @project.tasks.build], local:false) do |f|
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :title
    = f.text_area :title, :class => "tinymce", :rows => 10, :cols => 120
  .field
    = f.label :status
    = f.select(:status,[['Важный', 1],['Средний', 2],['Можно отложить', 3],['Готово', 4],['Протестировано', 5]])
  .actions = f.submit :id => "form_add_task"

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.slim
p id="notice" = notice

h1 Projects

table class="table"
  thead
    tr
      th Ваши проекты
      th colspan="4"
  tbody
    - @projects.each do |project|
      tr
        td = image_tag project.image.thumb('50x50#').url
        td = project.name
        td = link_to 'Открыть', project, class: "btn btn-info"
        td = link_to 'Удалить', project, method: :delete, data: { confirm: 'Are you sure?' }
br

= link_to 'New Project', new_project_path

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.slim
= tinymce
p id="notice" = notice

.header_project
  .hp__name
    p
      strong = @project.name
      br
      = image_tag @project.image.thumb('50x50#').url
  .hp_action
    button class="btn btn-info" id="add_task" Создать задачу

.tasks
  .work_tasks
    strong #TODO
    - @project.tasks.each do |task|
      - if task.status <= 3
        .block_task
          .block_task__header
            b = link_to task.name, [task.project, task]
          .block_task__body
            p = task.title.html_safe
  .test_tasks
    strong Need check
    - @project.tasks.each do |task|
      - if task.status == 4
        .block_task
          .block_task__header
            b = link_to task.name, [task.project, task]
          .block_task__body
            p = task.title.html_safe
  .ready_tasks
    strong Ready
    - @project.tasks.each do |task|
      - if task.status == 5
        .block_task
          .block_task__header
            b = link_to task.name, [task.project, task]
          .block_task__body
            p = task.title.html_safe



.form_task
  .ft_close
    span x
  = render 'form-task', project: @project

= link_to 'Edit', edit_project_path(@project), class: "btn btn-success"
= link_to ' Back', projects_path, class: "btn btn-success"